name: black
on: pull_request
jobs:
  black:
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'black-patches') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
         with:
          ref: ${{ github.head_ref }}
      - name: black
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        run: |
          python -m pip install --upgrade pip
          pip install black
        run: |
          black --experimental-string-processing .
      - name: Set black branch name
        id: vars
        run: echo ::set-output name=branch-name::"black-patches/${{ github.head_ref }}"
      - name: Create Pull Request
        if: steps.black.outputs.exit-code == 2
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: black action fixes
          title: Fixes by black action
          body: This is an auto-generated PR with fixes by black.
          labels: black, automated pr
          reviewers: peter-evans
          branch: ${{ steps.vars.outputs.branch-name }}
      - name: Fail if black made changes
        if: steps.black.outputs.exit-code == 2
        run: exit 1
